import { expect, test } from "vitest";
// This relative cross-package import is deliberate — the (opsLimit, memLimit)
// → wasm (mem_limit, ops_limit) argument swap lives in that TS layer and can
// only be proven there.
import {
    deriveKey,
    deriveKeyInsufficientMemoryErrorMessage,
    normalizeDerivedKeyError,
} from "../../accounts-rs/services/kdf";
import {
    auth_derive_kek,
    auth_generate_interactive_kek,
    auth_generate_sensitive_kek,
    auth_generate_srp_setup,
    auth_recovery_key_from_mnemonic_or_hex,
    auth_recovery_key_to_mnemonic,
    crypto_decrypt_box,
    crypto_generate_key,
} from "../pkg/ente_wasm.js";

// Generated by a Node script importing libsodium-wrappers-sumo and calling
// crypto_pwhash(32, password, salt16x42, ops, mem, ALG_ARGON2ID13) and
// crypto_secretbox_easy(plaintext32x5a, nonce24x24, interactiveKek), then
// base64-encoding the results.
const FIXTURE_PASSWORD = "ente-kdf-compat-fixture";
const FIXTURE_SALT = "QkJCQkJCQkJCQkJCQkJCQg==";
const LOW_COST_KEK = "ZHIKcIMyH98qeKLydKd848lsyM9pV+BplrVTTtAicuw=";
const INTERACTIVE_KEK = "AzOXMP53u88KH4RG8lvWxg/Ngtzd9bEXOh8PyoACMIU=";
const FIXTURE_PLAINTEXT =
    "WlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlo=";
const FIXTURE_NONCE = "JCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQk";
const FIXTURE_CIPHERTEXT =
    "ZWMWC3ASLxyG45WW04xiAw5yoj8MqBNqi5NxuzX1B3clvnqSZ5lAwM5bWonpgBQ4";

test("generates an interactive kek bundle", () => {
    const generated = auth_generate_interactive_kek(
        "correct horse battery staple",
    );

    expect(Buffer.from(generated.key, "base64")).toHaveLength(32);
    expect(Buffer.from(generated.salt, "base64")).toHaveLength(16);
    expect(generated.mem_limit).toBe(67_108_864);
    expect(generated.ops_limit).toBe(2);
});

test("generates a sensitive kek bundle", () => {
    const generated = auth_generate_sensitive_kek(
        "correct horse battery staple",
    );

    expect(Buffer.from(generated.key, "base64")).toHaveLength(32);
    expect(Buffer.from(generated.salt, "base64")).toHaveLength(16);
    expect(generated.mem_limit).toBeGreaterThan(0);
    expect(generated.ops_limit).toBeGreaterThan(0);
});

test("generates SRP setup attributes from a kek", () => {
    const kek = crypto_generate_key();
    const generated = auth_generate_srp_setup(kek, "test-user-id");

    expect(Buffer.from(generated.srp_salt, "base64")).toHaveLength(16);
    expect(Buffer.from(generated.login_sub_key, "base64")).toHaveLength(16);
    expect(
        Buffer.from(generated.srp_verifier, "base64").length,
    ).toBeGreaterThan(0);
});

test("round-trips recovery key mnemonic", () => {
    const recoveryKey = crypto_generate_key();
    const mnemonic = auth_recovery_key_to_mnemonic(recoveryKey);
    const decoded = auth_recovery_key_from_mnemonic_or_hex(mnemonic);

    expect(decoded).toBe(recoveryKey);
});

test("legacy KEK parity", () => {
    expect(auth_derive_kek(FIXTURE_PASSWORD, FIXTURE_SALT, 16384, 1)).toBe(
        LOW_COST_KEK,
    );
    expect(auth_derive_kek(FIXTURE_PASSWORD, FIXTURE_SALT, 67108864, 2)).toBe(
        INTERACTIVE_KEK,
    );
});

test("mem/ops argument order", async () => {
    expect(() =>
        auth_derive_kek(FIXTURE_PASSWORD, FIXTURE_SALT, 1, 16384),
    ).toThrow();
    await expect(
        deriveKey(FIXTURE_PASSWORD, FIXTURE_SALT, 1, 16384),
    ).resolves.toBe(LOW_COST_KEK);
});

test("legacy encrypted data remains readable", () => {
    expect(
        crypto_decrypt_box(
            FIXTURE_CIPHERTEXT,
            FIXTURE_NONCE,
            INTERACTIVE_KEK,
        ),
    ).toBe(FIXTURE_PLAINTEXT);
});

test("insufficient-memory error normalization", () => {
    let caught: unknown;

    try {
        auth_derive_kek(FIXTURE_PASSWORD, FIXTURE_SALT, 4096, 1);
    } catch (error) {
        caught = error;
    }

    expect(caught).toBeDefined();
    expect(caught).not.toBeInstanceOf(Error);
    expect(normalizeDerivedKeyError(caught).message).toBe(
        deriveKeyInsufficientMemoryErrorMessage,
    );
    expect(
        normalizeDerivedKeyError(
            Object.assign(new Error("x"), { code: "insufficient_memory" }),
        ).message,
    ).toBe(deriveKeyInsufficientMemoryErrorMessage);
    expect(
        normalizeDerivedKeyError(new Error("...insufficient memory..."))
            .message,
    ).toBe(deriveKeyInsufficientMemoryErrorMessage);

    const unrelatedError = new Error("unrelated failure");
    expect(normalizeDerivedKeyError(unrelatedError)).toBe(unrelatedError);
    expect(normalizeDerivedKeyError(unrelatedError).message).toBe(
        "unrelated failure",
    );
});
